### ISSUE TITLE
Add VM migration forecast API

### ISSUE THREAD

**Issue by zexi** [yunionio/yunioncloud#11165]
**What would you like to be added**:

According to the issue https://github.com/yunionio/yunioncloud/issues/11132, an API for VM migration prediction needs to be implemented at the backend.

The command line for climc is as follows:

```bash
$ climc server-migrate-forecast \
            --prefer-host $host-id \
            --live-migrate \
            --skip-cpu-check \
            $VM_ID_OR_NAME
```

REST API request: 

| Key    | Value                                                                       |
|--------|-----------------------------------------------------------------------------|
| Method | POST                                                                        |
| URL    | /servers/$server_id/migrate-forecast                                        |
| Body   | {"live_migrate":true, "skip_cpu_check": false, "prefer_host_id": "hostname"} |

**Comment by zexi** [comment]
YAML response examples are follows.

Response of not found host to migrate:

```yaml
allow_count: 0
can_create: false
candidates: null
filtered_candidates:
- filter_name: host_status
  id: 313e9087-2d0b-4ec6-8cf1-0264e4df8fe1
  name: office-02-host04
  reasons:
  - status is 'unknown', expected 'running'
  - host_status is 'offline', expected 'online'
  - enable_status is 'false', expected 'true'
- filter_name: host_status
  id: 6d70b50f-a9a2-43f2-82af-d03ac2e28816
  name: office-05-host05
  reasons:
  - status is 'unknown', expected 'running'
  - host_status is 'offline', expected 'online'
  - enable_status is 'false', expected 'true'
- filter_name: host_migrate
  id: 3bce9607-2597-469f-8d9b-977345456739
  name: office-99-host03
  reasons:
  - host cpu mode not match for live migrate
- filter_name: host_migrate
  id: 55656ee6-f134-4ddf-84e1-c517cd717178
  name: office-03-host01
  reasons:
  - host_id specified for migration
- filter_name: host_schedtag
  id: 069054dd-ba20-4865-8c9a-64eaf169f543
  name: office-04-host02
  reasons:
  - 'schedtag: schedtag "exclude-sql-host" exclude hosts:office-04-host02:069054dd-ba20-4865-8c9a-64eaf169f543'
not_allow_reasons:
- Out of resource
req_count: 1
```

Response of host to migrate:

```yaml
allow_count: 1
can_create: true
candidates:
- backup_candidate: null
  disks:
  - index: 0
    storage_ids:
    - 5862edf6-763b-4566-82b1-542f9c4f5b13
  - index: 1
    storage_ids:
    - 5862edf6-763b-4566-82b1-542f9c4f5b13
  error: ""
  host_id: 16bb71fd-d246-4412-8f92-0434d81eb735
  name: 10-127-40-2
  nets:
  - index: 0
    network_ids:
    - c345894e-5b00-4d1d-8654-ad5139ef9cb3
  session_id: "1621485547284"
filtered_candidates: []
not_allow_reasons: null
req_count: 1
```
